### ISSUE TITLE
Name of the Repo

### ISSUE THREAD

**Issue by ke-sun** [kartikmohta/qualisys#3]
ROS will generate warnings during the compilation if the package name start with a capital letter. Maybe consider change the name of the repo to qualisys instead.

For feature/catkin branch, I have already change the name of the package to qualisys in files like CMakeList.txt and package.xml. Simply change the name of the package once it is cloned, otherwise it won't compile.

**Comment by kartikmohta** [comment]
I'll rename the repository to qualisys, make sure you change the remote repository url in your git config to point to the new one.
