### ISSUE TITLE
Merge vicon and qualisys into mocap

### ISSUE THREAD

**Issue by versatran01** [kartikmohta/qualisys#5]
Seems like there are a lot of duplicated code in vicon and qualisys, e.g. vicon_odom, qualisys_odom.
Since both of the above packages only need to know the `ViconSubject` message, there's no point in having two of them.

I propose that we merge vicon and qualysis into a new package called mocap.
The package structure will look like this

```
\mocap
    \vicon
    \qualysis
    \mocap_msgs
    \mocap_odom
```

The `mocap_odom` could be named something else, and one should be able to specify whether he wants `Odom` or `Pose`.

Note that this proposal is to create a new package, thus who ever don't want to move can still use the old qualysis or vicon.

**Comment by ke-sun** [comment]
I will look into this.

**Comment by ke-sun** [comment]
For the new merged package, I am thinking of getting rid of *_odom and *_calib functionality. And the driver itself will publish the /subject/odom msgs for all the active subjects. Once the driver is launched, no other odom node is needed.

Also, @versatran01 suggested that geometry_msgs/PoseStamped can be published as needed is the last post.

So, what other suggestions you guys have?

**Comment by versatran01** [comment]
@kartikmohta 
Can we move this repo to KumarRobotics? Issues here are only visible to the three of us. 
It would be nice if people who will be using the driver can join such discussion.

**Comment by kartikmohta** [comment]
@ke-sun Wanted to keep the odom functionality independent, so that one node is not doing too much work. Not opposed to merging them if done properly

@versatran01 Yes will transfer to KumarRobotics now that this is stable

**Comment by kartikmohta** [comment]
See https://github.com/KumarRobotics/motion_capture_system
